import { getAutoCaptionsConfigCached } from '../../caption-generator/data-access/caption-config.mjs';

// The track URL prefix is deployment-controlled. By default, point at this
// processor's own /api/captions/track route. The Next.js (or any front-end
// proxy) can override with CAPTIONS_TRACK_URL_PREFIX if it wants the player to
// hit a proxy route — useful for server-side auth, edge caching, or hiding the
// processor URL from the browser.
//   default: ${FILE_SERVER_NODE_URL}/api/captions/track
//   override e.g.: CAPTIONS_TRACK_URL_PREFIX=https://app.example.com/api/authenticated/subtitles
const TRACK_URL_PREFIX =
  process.env.CAPTIONS_TRACK_URL_PREFIX ||
  `${process.env.FILE_SERVER_NODE_URL || ''}/api/captions/track`;

/**
 * Build the public URL for the track endpoint. Movies vs TV have different shapes.
 * Path shape is fixed across deployments so a proxy can route on it:
 *   /movie/:title/:lang
 *   /tv/:show/:lang/:season/:episode
 */
function buildTrackUrl({ mediaType, mediaTitle, season, episode }, langCode) {
  const t = encodeURIComponent(mediaTitle);
  const l = encodeURIComponent(langCode);
  if (mediaType === 'movie') return `${TRACK_URL_PREFIX}/movie/${t}/${l}`;
  return `${TRACK_URL_PREFIX}/tv/${t}/${l}/${encodeURIComponent(season)}/${encodeURIComponent(episode)}`;
}

/**
 * For each enabled language in app_config.autoCaptions, mutate-in a "pending"
 * stub entry pointing at the track endpoint so the frontend can surface the
 * option before generation runs.
 *
 * Auto-generated tracks are offered as an *alternative* alongside any
 * human-authored subtitle for the same language — the user can switch to the
 * auto track if the human one is missing, wrong, or out of sync. Distinct
 * scanner keys ("English" vs "English - Auto Generated") keep them separate
 * in the player's track list.
 *
 * Skips only when:
 *  - feature disabled, or
 *  - an `.auto.srt` for that language already exists on disk (the scanner
 *    will have emitted a real entry under the same display key, which we'd
 *    shadow with a stub).
 *
 * @param {Object} subtitles - Subtitles map keyed by display name; mutated in place.
 * @param {Object} ctx       - { mediaType, mediaTitle, season?, episode?, langMap }
 */
export async function addCaptionStubs(subtitles, ctx) {
  const config = await getAutoCaptionsConfigCached().catch(() => null);
  if (!config || !config.enabled || !Array.isArray(config.languages)) return;

  for (const langCode of config.languages) {
    const langName = (ctx.langMap && ctx.langMap[langCode]) || langCode;
    const stubKey = `${langName} - Auto Generated`;
    if (subtitles[stubKey]) continue;

    subtitles[stubKey] = {
      url: buildTrackUrl(ctx, langCode),
      srcLang: langCode,
      autoGenerated: true,
      pending: true
    };
  }
}
