import { describe, it, expect, beforeEach, jest } from '@jest/globals';

// Mock the cached config getter so we control the result per test.
const mockGetConfig = jest.fn();
jest.unstable_mockModule(
  '../../../components/caption-generator/data-access/caption-config.mjs',
  () => ({ getAutoCaptionsConfigCached: mockGetConfig })
);

const { addCaptionStubs, injectMovieStubs, injectTvStubs } = await import(
  '../../../components/caption-generator/domain/caption-stubs.mjs'
);

const langMap = { en: 'English', es: 'Spanish' };

// A video's audio as the scanner records it (additionalMetadata.audio).
function scannedAudio(...languageTags) {
  return {
    audio: languageTags.map((languageTag, position) => ({
      codec: 'eac3',
      channels: 6,
      language: languageTag,
      languageTag,
      title: null,
      disposition: { default: position === 0, comment: false, visual_impaired: false, descriptions: false }
    }))
  };
}

// The same tracks as addCaptionStubs takes them (tracksFromScanMetadata).
function audioTracks(...languages) {
  return languages.map((language, index) => ({
    index,
    channels: 6,
    language,
    title: null,
    isDefault: index === 0,
    commentary: false,
    described: false
  }));
}

describe('addCaptionStubs', () => {
  beforeEach(() => mockGetConfig.mockReset());

  it('does nothing when feature is disabled', async () => {
    mockGetConfig.mockResolvedValue({ enabled: false, languages: ['en'] });
    const subs = {};
    await addCaptionStubs(subs, { mediaType: 'movie', mediaTitle: 'Movie', langMap, audioTracks: audioTracks('eng') });
    expect(subs).toEqual({});
  });

  it('emits a stub for each enabled language not already present', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en', 'es'] });
    const subs = {};
    await addCaptionStubs(subs, { mediaType: 'movie', mediaTitle: 'Movie', langMap, audioTracks: audioTracks('eng', 'spa') });
    expect(Object.keys(subs).sort()).toEqual([
      'English - Auto Generated',
      'Spanish - Auto Generated'
    ]);
    expect(subs['English - Auto Generated']).toMatchObject({
      srcLang: 'en',
      autoGenerated: true,
      pending: true
    });
    expect(subs['English - Auto Generated'].url).toContain('/api/captions/track/movie/Movie/en');
  });

  it('still emits an auto stub when a same-lang human sub already exists (alternative track)', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en', 'es'] });
    const subs = {
      English: { url: '/movies/foo/foo.en.srt', srcLang: 'en' }
    };
    await addCaptionStubs(subs, { mediaType: 'movie', mediaTitle: 'Movie', langMap, audioTracks: audioTracks('eng', 'spa') });
    // The human "English" track stays; the auto-generated alternative is added too.
    expect(Object.keys(subs).sort()).toEqual([
      'English',
      'English - Auto Generated',
      'Spanish - Auto Generated'
    ]);
    expect(subs['English']).toEqual({ url: '/movies/foo/foo.en.srt', srcLang: 'en' });
    expect(subs['English - Auto Generated']).toMatchObject({
      srcLang: 'en',
      autoGenerated: true,
      pending: true
    });
  });

  it('skips when an .auto entry for the same language already exists', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en'] });
    const subs = {
      'English - Auto Generated': {
        url: '/movies/foo/foo.en.auto.srt',
        srcLang: 'en',
        autoGenerated: true
      }
    };
    await addCaptionStubs(subs, { mediaType: 'movie', mediaTitle: 'Movie', langMap, audioTracks: audioTracks('eng') });
    expect(subs['English - Auto Generated'].pending).toBeUndefined();
  });

  it('builds a tv-shaped track URL', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en'] });
    const subs = {};
    await addCaptionStubs(subs, {
      mediaType: 'tv',
      mediaTitle: 'My Show',
      season: '01',
      episode: '03',
      langMap,
      audioTracks: audioTracks('eng')
    });
    expect(subs['English - Auto Generated'].url).toContain('/api/captions/track/tv/My%20Show/en/01/03');
  });

  it('falls back to lang code when not in langMap', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['zz'] });
    const subs = {};
    await addCaptionStubs(subs, { mediaType: 'movie', mediaTitle: 'Movie', langMap, audioTracks: audioTracks('zz') });
    expect(subs['zz - Auto Generated']).toMatchObject({ srcLang: 'zz' });
  });

  it('silently skips on config read failure', async () => {
    mockGetConfig.mockRejectedValue(new Error('mongo down'));
    const subs = {};
    await addCaptionStubs(subs, { mediaType: 'movie', mediaTitle: 'Movie', langMap, audioTracks: audioTracks('eng') });
    expect(subs).toEqual({});
  });

  // A caption is only made from a track tagged with its language, so it is
  // only offered where there is one.
  it('offers no caption for a video with no audio track in that language', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en'] });
    const subs = {};
    await addCaptionStubs(subs, { mediaType: 'movie', mediaTitle: 'Movie', langMap, audioTracks: audioTracks('ita', 'jpn') });
    expect(subs).toEqual({});
  });

  it('offers each language only where the video has it', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en', 'es'] });
    const subs = {};
    await addCaptionStubs(subs, { mediaType: 'movie', mediaTitle: 'Movie', langMap, audioTracks: audioTracks('ita', 'spa') });
    expect(Object.keys(subs)).toEqual(['Spanish - Auto Generated']);
  });

  it('offers no caption for a video whose audio carries no language tag', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en'] });
    const subs = {};
    await addCaptionStubs(subs, { mediaType: 'movie', mediaTitle: 'Movie', langMap, audioTracks: audioTracks(null) });
    expect(subs).toEqual({});
  });

  it('offers no caption when the audio tracks are not known', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en'] });
    for (const unknown of [null, undefined]) {
      const subs = {};
      await addCaptionStubs(subs, { mediaType: 'movie', mediaTitle: 'Movie', langMap, audioTracks: unknown });
      expect(subs).toEqual({});
    }
    const subs = {};
    await addCaptionStubs(subs, { mediaType: 'movie', mediaTitle: 'Movie', langMap });
    expect(subs).toEqual({});
  });

  it('leaves a finished auto caption listed whatever the audio says', async () => {
    // The file is on disk; whether it should be is the audit's question, not the stub's.
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en'] });
    const subs = {
      'English - Auto Generated': { url: '/movies/foo/foo.en.auto.srt', srcLang: 'en', autoGenerated: true }
    };
    await addCaptionStubs(subs, { mediaType: 'movie', mediaTitle: 'Movie', langMap, audioTracks: audioTracks('ita') });
    expect(Object.keys(subs)).toEqual(['English - Auto Generated']);
  });
});

describe('injectMovieStubs', () => {
  beforeEach(() => mockGetConfig.mockReset());

  it('injects stubs into movie.urls.subtitles for each movie', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en'] });
    const movies = [
      { name: 'Movie A', urls: { subtitles: { English: { srcLang: 'en' } } }, additional_metadata: scannedAudio('eng') },
      { name: 'Movie B', urls: {}, additional_metadata: scannedAudio('ita', 'eng') }
    ];
    await injectMovieStubs(movies, langMap);

    expect(movies[0].urls.subtitles['English - Auto Generated']).toMatchObject({
      srcLang: 'en',
      autoGenerated: true,
      pending: true
    });
    expect(movies[1].urls.subtitles['English - Auto Generated']).toMatchObject({
      srcLang: 'en',
      pending: true
    });
  });

  it('offers the caption only on the movies whose video has audio in that language', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en'] });
    const movies = [
      { name: 'English', urls: {}, additional_metadata: scannedAudio('eng') },
      { name: 'Dubbed', urls: {}, additional_metadata: scannedAudio('ger', 'eng') },
      { name: 'Italian', urls: { subtitles: { English: { srcLang: 'en' } } }, additional_metadata: scannedAudio('ita') },
      { name: 'Italian, no subs', urls: {}, additional_metadata: scannedAudio('ita') },
      { name: 'Untagged', urls: {}, additional_metadata: scannedAudio(null) },
      { name: 'Not scanned', urls: {}, additional_metadata: {} },
      { name: 'No record', urls: {} }
    ];
    await injectMovieStubs(movies, langMap);

    const offered = movies.filter((movie) => movie.urls.subtitles?.['English - Auto Generated']).map((movie) => movie.name);
    expect(offered).toEqual(['English', 'Dubbed']);
    // The human track is untouched, and a movie left with no subtitles has no subtitles key.
    expect(movies[2].urls.subtitles).toEqual({ English: { srcLang: 'en' } });
    expect(movies[3].urls.subtitles).toBeUndefined();
  });

  it('omits subtitles object entirely when feature disabled and no human subs', async () => {
    mockGetConfig.mockResolvedValue({ enabled: false, languages: ['en'] });
    const movies = [{ name: 'Movie A', urls: {}, additional_metadata: scannedAudio('eng') }];
    await injectMovieStubs(movies, langMap);
    expect(movies[0].urls.subtitles).toBeUndefined();
  });

  it('handles malformed input gracefully', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en'] });
    await expect(injectMovieStubs(null, langMap)).resolves.toBeUndefined();
    await expect(injectMovieStubs(undefined, langMap)).resolves.toBeUndefined();
    const movies = [null, { name: 'X' }, { name: 'Y', urls: null }];
    await injectMovieStubs(movies, langMap);
    // None should crash; movies without urls don't get subtitles.
    expect(movies[1].urls).toBeUndefined();
  });
});

describe('injectTvStubs', () => {
  beforeEach(() => mockGetConfig.mockReset());

  it('injects stubs into each episode keyed by show / season / episode', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en'] });
    const shows = [
      {
        name: 'Some Show',
        seasons: {
          'Season 1': {
            episodes: {
              S01E01: { subtitles: { English: { srcLang: 'en' } }, additionalMetadata: scannedAudio('eng') },
              S01E02: { additionalMetadata: scannedAudio('eng') }
            }
          },
          'Season 2': {
            episodes: {
              S02E03: { additionalMetadata: scannedAudio('eng') }
            }
          }
        }
      }
    ];
    await injectTvStubs(shows, langMap);

    const ep1 = shows[0].seasons['Season 1'].episodes.S01E01;
    const ep2 = shows[0].seasons['Season 1'].episodes.S01E02;
    const ep3 = shows[0].seasons['Season 2'].episodes.S02E03;

    expect(ep1.subtitles['English - Auto Generated'].url).toContain('/api/captions/track/tv/Some%20Show/en/01/01');
    expect(ep2.subtitles['English - Auto Generated'].url).toContain('/api/captions/track/tv/Some%20Show/en/01/02');
    expect(ep3.subtitles['English - Auto Generated'].url).toContain('/api/captions/track/tv/Some%20Show/en/02/03');
  });

  it('offers the caption only on the episodes whose video has audio in that language', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en'] });
    const shows = [
      {
        name: 'Mixed Show',
        seasons: {
          'Season 1': {
            episodes: {
              S01E01: { additionalMetadata: scannedAudio('fre', 'eng') },
              S01E02: { additionalMetadata: scannedAudio('fre') },
              S01E03: { additionalMetadata: scannedAudio(null) },
              S01E04: {}
            }
          }
        }
      }
    ];
    await injectTvStubs(shows, langMap);

    const episodes = shows[0].seasons['Season 1'].episodes;
    expect(episodes.S01E01.subtitles['English - Auto Generated']).toMatchObject({ pending: true });
    expect(episodes.S01E02.subtitles).toBeUndefined();
    expect(episodes.S01E03.subtitles).toBeUndefined();
    expect(episodes.S01E04.subtitles).toBeUndefined();
  });

  it('skips episodes whose key does not match S\\d+E\\d+', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en'] });
    const shows = [
      {
        name: 'Weird Show',
        seasons: {
          'Season 1': {
            episodes: {
              extras: { additionalMetadata: scannedAudio('eng') },      // does not match the SxxExx pattern
              S01E01: { additionalMetadata: scannedAudio('eng') }
            }
          }
        }
      }
    ];
    await injectTvStubs(shows, langMap);
    expect(shows[0].seasons['Season 1'].episodes.extras.subtitles).toBeUndefined();
    expect(shows[0].seasons['Season 1'].episodes.S01E01.subtitles).toBeDefined();
  });

  it('handles malformed input gracefully', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en'] });
    await expect(injectTvStubs(null, langMap)).resolves.toBeUndefined();
    await expect(injectTvStubs([null, {}, { seasons: null }], langMap)).resolves.toBeUndefined();
  });
});
