import { describe, it, expect, beforeEach, jest } from '@jest/globals';

// Mock the cached config getter so we control the result per test.
const mockGetConfig = jest.fn();
jest.unstable_mockModule(
  '../../../components/caption-generator/data-access/caption-config.mjs',
  () => ({ getAutoCaptionsConfigCached: mockGetConfig })
);

const { addCaptionStubs, injectMovieStubs, injectTvStubs } = await import(
  '../../../components/caption-generator/domain/caption-stubs.mjs'
);

const langMap = { en: 'English', es: 'Spanish' };

describe('addCaptionStubs', () => {
  beforeEach(() => mockGetConfig.mockReset());

  it('does nothing when feature is disabled', async () => {
    mockGetConfig.mockResolvedValue({ enabled: false, languages: ['en'] });
    const subs = {};
    await addCaptionStubs(subs, { mediaType: 'movie', mediaTitle: 'Movie', langMap });
    expect(subs).toEqual({});
  });

  it('emits a stub for each enabled language not already present', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en', 'es'] });
    const subs = {};
    await addCaptionStubs(subs, { mediaType: 'movie', mediaTitle: 'Movie', langMap });
    expect(Object.keys(subs).sort()).toEqual([
      'English - Auto Generated',
      'Spanish - Auto Generated'
    ]);
    expect(subs['English - Auto Generated']).toMatchObject({
      srcLang: 'en',
      autoGenerated: true,
      pending: true
    });
    expect(subs['English - Auto Generated'].url).toContain('/api/captions/track/movie/Movie/en');
  });

  it('still emits an auto stub when a same-lang human sub already exists (alternative track)', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en', 'es'] });
    const subs = {
      English: { url: '/movies/foo/foo.en.srt', srcLang: 'en' }
    };
    await addCaptionStubs(subs, { mediaType: 'movie', mediaTitle: 'Movie', langMap });
    // The human "English" track stays; the auto-generated alternative is added too.
    expect(Object.keys(subs).sort()).toEqual([
      'English',
      'English - Auto Generated',
      'Spanish - Auto Generated'
    ]);
    expect(subs['English']).toEqual({ url: '/movies/foo/foo.en.srt', srcLang: 'en' });
    expect(subs['English - Auto Generated']).toMatchObject({
      srcLang: 'en',
      autoGenerated: true,
      pending: true
    });
  });

  it('skips when an .auto entry for the same language already exists', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en'] });
    const subs = {
      'English - Auto Generated': {
        url: '/movies/foo/foo.en.auto.srt',
        srcLang: 'en',
        autoGenerated: true
      }
    };
    await addCaptionStubs(subs, { mediaType: 'movie', mediaTitle: 'Movie', langMap });
    expect(subs['English - Auto Generated'].pending).toBeUndefined();
  });

  it('builds a tv-shaped track URL', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en'] });
    const subs = {};
    await addCaptionStubs(subs, {
      mediaType: 'tv',
      mediaTitle: 'My Show',
      season: '01',
      episode: '03',
      langMap
    });
    expect(subs['English - Auto Generated'].url).toContain('/api/captions/track/tv/My%20Show/en/01/03');
  });

  it('falls back to lang code when not in langMap', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['zz'] });
    const subs = {};
    await addCaptionStubs(subs, { mediaType: 'movie', mediaTitle: 'Movie', langMap });
    expect(subs['zz - Auto Generated']).toMatchObject({ srcLang: 'zz' });
  });

  it('silently skips on config read failure', async () => {
    mockGetConfig.mockRejectedValue(new Error('mongo down'));
    const subs = {};
    await addCaptionStubs(subs, { mediaType: 'movie', mediaTitle: 'Movie', langMap });
    expect(subs).toEqual({});
  });
});

describe('injectMovieStubs', () => {
  beforeEach(() => mockGetConfig.mockReset());

  it('injects stubs into movie.urls.subtitles for each movie', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en'] });
    const movies = [
      { name: 'Movie A', urls: { subtitles: { English: { srcLang: 'en' } } } },
      { name: 'Movie B', urls: {} }
    ];
    await injectMovieStubs(movies, langMap);

    expect(movies[0].urls.subtitles['English - Auto Generated']).toMatchObject({
      srcLang: 'en',
      autoGenerated: true,
      pending: true
    });
    expect(movies[1].urls.subtitles['English - Auto Generated']).toMatchObject({
      srcLang: 'en',
      pending: true
    });
  });

  it('omits subtitles object entirely when feature disabled and no human subs', async () => {
    mockGetConfig.mockResolvedValue({ enabled: false, languages: ['en'] });
    const movies = [{ name: 'Movie A', urls: {} }];
    await injectMovieStubs(movies, langMap);
    expect(movies[0].urls.subtitles).toBeUndefined();
  });

  it('handles malformed input gracefully', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en'] });
    await expect(injectMovieStubs(null, langMap)).resolves.toBeUndefined();
    await expect(injectMovieStubs(undefined, langMap)).resolves.toBeUndefined();
    const movies = [null, { name: 'X' }, { name: 'Y', urls: null }];
    await injectMovieStubs(movies, langMap);
    // None should crash; movies without urls don't get subtitles.
    expect(movies[1].urls).toBeUndefined();
  });
});

describe('injectTvStubs', () => {
  beforeEach(() => mockGetConfig.mockReset());

  it('injects stubs into each episode keyed by show / season / episode', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en'] });
    const shows = [
      {
        name: 'Some Show',
        seasons: {
          'Season 1': {
            episodes: {
              S01E01: { subtitles: { English: { srcLang: 'en' } } },
              S01E02: {}
            }
          },
          'Season 2': {
            episodes: {
              S02E03: {}
            }
          }
        }
      }
    ];
    await injectTvStubs(shows, langMap);

    const ep1 = shows[0].seasons['Season 1'].episodes.S01E01;
    const ep2 = shows[0].seasons['Season 1'].episodes.S01E02;
    const ep3 = shows[0].seasons['Season 2'].episodes.S02E03;

    expect(ep1.subtitles['English - Auto Generated'].url).toContain('/api/captions/track/tv/Some%20Show/en/01/01');
    expect(ep2.subtitles['English - Auto Generated'].url).toContain('/api/captions/track/tv/Some%20Show/en/01/02');
    expect(ep3.subtitles['English - Auto Generated'].url).toContain('/api/captions/track/tv/Some%20Show/en/02/03');
  });

  it('skips episodes whose key does not match S\\d+E\\d+', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en'] });
    const shows = [
      {
        name: 'Weird Show',
        seasons: {
          'Season 1': {
            episodes: {
              extras: {},      // does not match the SxxExx pattern
              S01E01: {}
            }
          }
        }
      }
    ];
    await injectTvStubs(shows, langMap);
    expect(shows[0].seasons['Season 1'].episodes.extras.subtitles).toBeUndefined();
    expect(shows[0].seasons['Season 1'].episodes.S01E01.subtitles).toBeDefined();
  });

  it('handles malformed input gracefully', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en'] });
    await expect(injectTvStubs(null, langMap)).resolves.toBeUndefined();
    await expect(injectTvStubs([null, {}, { seasons: null }], langMap)).resolves.toBeUndefined();
  });
});
