import { describe, it, expect, beforeEach, jest } from '@jest/globals';

// Mock the cached config getter so we control the result per test.
const mockGetConfig = jest.fn();
jest.unstable_mockModule(
  '../../../components/caption-generator/data-access/caption-config.mjs',
  () => ({ getAutoCaptionsConfigCached: mockGetConfig })
);

const { addCaptionStubs } = await import('../../../components/media-scanner/domain/caption-stubs.mjs');

const langMap = { en: 'English', es: 'Spanish' };

describe('addCaptionStubs', () => {
  beforeEach(() => mockGetConfig.mockReset());

  it('does nothing when feature is disabled', async () => {
    mockGetConfig.mockResolvedValue({ enabled: false, languages: ['en'] });
    const subs = {};
    await addCaptionStubs(subs, { mediaType: 'movie', mediaTitle: 'Movie', langMap });
    expect(subs).toEqual({});
  });

  it('emits a stub for each enabled language not already present', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en', 'es'] });
    const subs = {};
    await addCaptionStubs(subs, { mediaType: 'movie', mediaTitle: 'Movie', langMap });
    expect(Object.keys(subs).sort()).toEqual([
      'English - Auto Generated',
      'Spanish - Auto Generated'
    ]);
    expect(subs['English - Auto Generated']).toMatchObject({
      srcLang: 'en',
      autoGenerated: true,
      pending: true
    });
    expect(subs['English - Auto Generated'].url).toContain('/api/captions/track/movie/Movie/en');
  });

  it('still emits an auto stub when a same-lang human sub already exists (alternative track)', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en', 'es'] });
    const subs = {
      English: { url: '/movies/foo/foo.en.srt', srcLang: 'en' }
    };
    await addCaptionStubs(subs, { mediaType: 'movie', mediaTitle: 'Movie', langMap });
    // The human "English" track stays; the auto-generated alternative is added too.
    expect(Object.keys(subs).sort()).toEqual([
      'English',
      'English - Auto Generated',
      'Spanish - Auto Generated'
    ]);
    expect(subs['English']).toEqual({ url: '/movies/foo/foo.en.srt', srcLang: 'en' });
    expect(subs['English - Auto Generated']).toMatchObject({
      srcLang: 'en',
      autoGenerated: true,
      pending: true
    });
  });

  it('skips when an .auto entry for the same language already exists', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en'] });
    const subs = {
      'English - Auto Generated': {
        url: '/movies/foo/foo.en.auto.srt',
        srcLang: 'en',
        autoGenerated: true
      }
    };
    await addCaptionStubs(subs, { mediaType: 'movie', mediaTitle: 'Movie', langMap });
    expect(subs['English - Auto Generated'].pending).toBeUndefined();
  });

  it('builds a tv-shaped track URL', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['en'] });
    const subs = {};
    await addCaptionStubs(subs, {
      mediaType: 'tv',
      mediaTitle: 'My Show',
      season: '01',
      episode: '03',
      langMap
    });
    expect(subs['English - Auto Generated'].url).toContain('/api/captions/track/tv/My%20Show/en/01/03');
  });

  it('falls back to lang code when not in langMap', async () => {
    mockGetConfig.mockResolvedValue({ enabled: true, languages: ['zz'] });
    const subs = {};
    await addCaptionStubs(subs, { mediaType: 'movie', mediaTitle: 'Movie', langMap });
    expect(subs['zz - Auto Generated']).toMatchObject({ srcLang: 'zz' });
  });

  it('silently skips on config read failure', async () => {
    mockGetConfig.mockRejectedValue(new Error('mongo down'));
    const subs = {};
    await addCaptionStubs(subs, { mediaType: 'movie', mediaTitle: 'Movie', langMap });
    expect(subs).toEqual({});
  });
});
