import { getAutoCaptionsConfigCached } from '../data-access/caption-config.mjs';
import { hasCaptionAudioTrack, tracksFromScanMetadata } from './audio-track.mjs';

// The track URL prefix is deployment-controlled. By default, point at this
// processor's own /api/captions/track route. The Next.js (or any front-end
// proxy) can override with CAPTIONS_TRACK_URL_PREFIX if it wants the player to
// hit a proxy route — useful for server-side auth, edge caching, or hiding the
// processor URL from the browser.
//   default: ${FILE_SERVER_NODE_URL}/api/captions/track
//   override e.g.: CAPTIONS_TRACK_URL_PREFIX=https://app.example.com/api/authenticated/subtitles
const TRACK_URL_PREFIX =
  process.env.CAPTIONS_TRACK_URL_PREFIX ||
  `${process.env.FILE_SERVER_NODE_URL || ''}/api/captions/track`;

/**
 * Build the public URL for the track endpoint. Movies vs TV have different shapes.
 * Path shape is fixed across deployments so a proxy can route on it:
 *   /movie/:title/:lang
 *   /tv/:show/:lang/:season/:episode
 */
function buildTrackUrl({ mediaType, mediaTitle, season, episode }, langCode) {
  const t = encodeURIComponent(mediaTitle);
  const l = encodeURIComponent(langCode);
  if (mediaType === 'movie') return `${TRACK_URL_PREFIX}/movie/${t}/${l}`;
  return `${TRACK_URL_PREFIX}/tv/${t}/${l}/${encodeURIComponent(season)}/${encodeURIComponent(episode)}`;
}

/**
 * For each enabled language in app_config.autoCaptions, mutate-in a "pending"
 * stub entry pointing at the track endpoint so the frontend can surface the
 * option before generation runs.
 *
 * Auto-generated tracks are offered as an *alternative* alongside any
 * human-authored subtitle for the same language — the user can switch to the
 * auto track if the human one is missing, wrong, or out of sync. Distinct
 * scanner keys ("English" vs "English - Auto Generated") keep them separate
 * in the player's track list.
 *
 * Skips only when:
 *  - feature disabled, or
 *  - an `.auto.srt` for that language already exists on disk (the scanner
 *    will have emitted a real entry under the same display key, which we'd
 *    shadow with a stub), or
 *  - the title's video is not known to have an audio track in that language.
 *    A caption is only ever made from a track tagged with its language
 *    (audio-track.mjs), so offering one anywhere else is offering a request
 *    that will be refused. "Not known" includes a record with no audio list:
 *    the option appears once a scan has recorded the tracks.
 *
 * @param {Object} subtitles - Subtitles map keyed by display name; mutated in place.
 * @param {Object} ctx       - { mediaType, mediaTitle, season?, episode?, langMap, audioTracks }
 *   `audioTracks`: the video's audio tracks as the scanner recorded them
 *   (`tracksFromScanMetadata`), or null when the record does not say.
 */
export async function addCaptionStubs(subtitles, ctx) {
  const config = await getAutoCaptionsConfigCached().catch(() => null);
  if (!config || !config.enabled || !Array.isArray(config.languages)) return;

  for (const langCode of config.languages) {
    const langName = (ctx.langMap && ctx.langMap[langCode]) || langCode;
    const stubKey = `${langName} - Auto Generated`;
    if (subtitles[stubKey]) continue;
    if (!hasCaptionAudioTrack(ctx.audioTracks, langCode)) continue;

    subtitles[stubKey] = {
      url: buildTrackUrl(ctx, langCode),
      srcLang: langCode,
      autoGenerated: true,
      pending: true
    };
  }
}

/**
 * Read-time injection for the /media/movies response. Mutates each movie's
 * `urls.subtitles` map in place to add pending stubs for any enabled lang.
 *
 * Doing this at read time (instead of scan time) means toggling the autoCaptions
 * flag, adding a language, or completing a generation job all take effect on
 * the very next request — no rescan required. Nothing is persisted.
 *
 * @param {Array} movies   - Records from getMovies()
 * @param {Object} langMap - Code → display-name map
 */
export async function injectMovieStubs(movies, langMap) {
  if (!Array.isArray(movies)) return;
  for (const movie of movies) {
    if (!movie || !movie.urls) continue;
    if (!movie.urls.subtitles) movie.urls.subtitles = {};
    await addCaptionStubs(movie.urls.subtitles, {
      mediaType: 'movie',
      mediaTitle: movie.name,
      langMap,
      audioTracks: tracksFromScanMetadata(movie.additional_metadata)
    });
    if (Object.keys(movie.urls.subtitles).length === 0) {
      delete movie.urls.subtitles;
    }
  }
}

/**
 * Read-time injection for the /media/tv response. Walks each show → season →
 * episode and adds pending stubs to `episode.subtitles`.
 *
 * @param {Array} shows    - Records from getTVShows()
 * @param {Object} langMap - Code → display-name map
 */
export async function injectTvStubs(shows, langMap) {
  if (!Array.isArray(shows)) return;
  for (const show of shows) {
    if (!show || !show.seasons) continue;
    for (const seasonName of Object.keys(show.seasons)) {
      const season = show.seasons[seasonName];
      if (!season || !season.episodes) continue;
      const seasonMatch = String(seasonName).match(/\d+/);
      const seasonNumber = seasonMatch ? seasonMatch[0].padStart(2, '0') : '00';
      for (const episodeKey of Object.keys(season.episodes)) {
        const episode = season.episodes[episodeKey];
        if (!episode) continue;
        const m = String(episodeKey).match(/S\d+E(\d+)/i);
        if (!m) continue;
        const episodeNumber = m[1].padStart(2, '0');
        if (!episode.subtitles) episode.subtitles = {};
        await addCaptionStubs(episode.subtitles, {
          mediaType: 'tv',
          mediaTitle: show.name,
          season: seasonNumber,
          episode: episodeNumber,
          langMap,
          audioTracks: tracksFromScanMetadata(episode.additionalMetadata)
        });
        if (Object.keys(episode.subtitles).length === 0) {
          delete episode.subtitles;
        }
      }
    }
  }
}
