import { describe, it, expect } from '@jest/globals';
import { parseSubtitleFilename } from '../../../components/media-scanner/domain/subtitle-filename.mjs';

const langMap = { en: 'English', es: 'Spanish', fr: 'French' };

describe('parseSubtitleFilename', () => {
  it('parses a plain language subtitle', () => {
    const r = parseSubtitleFilename('My Movie.en.srt', langMap);
    expect(r).toEqual({
      langCode: 'en',
      langName: 'English',
      subtitleKey: 'English',
      isHearingImpaired: false,
      isAutoGenerated: false
    });
  });

  it('parses hearing-impaired marker', () => {
    const r = parseSubtitleFilename('My Movie.en.hi.srt', langMap);
    expect(r.isHearingImpaired).toBe(true);
    expect(r.isAutoGenerated).toBe(false);
    expect(r.subtitleKey).toBe('English Hearing Impaired');
    expect(r.langCode).toBe('en');
  });

  it('parses auto-generated marker', () => {
    const r = parseSubtitleFilename('My Movie.en.auto.srt', langMap);
    expect(r.isAutoGenerated).toBe(true);
    expect(r.isHearingImpaired).toBe(false);
    expect(r.subtitleKey).toBe('English - Auto Generated');
    expect(r.langCode).toBe('en');
  });

  it('parses both modifiers regardless of order', () => {
    const a = parseSubtitleFilename('Show.S01E01.en.auto.hi.srt', langMap);
    const b = parseSubtitleFilename('Show.S01E01.en.hi.auto.srt', langMap);
    expect(a.langCode).toBe('en');
    expect(a.isHearingImpaired).toBe(true);
    expect(a.isAutoGenerated).toBe(true);
    expect(a.subtitleKey).toBe('English Hearing Impaired - Auto Generated');
    expect(b).toEqual(a);
  });

  it('falls back to the raw code when not in langMap', () => {
    const r = parseSubtitleFilename('Movie.zz.srt', langMap);
    expect(r.langCode).toBe('zz');
    expect(r.langName).toBe('zz');
    expect(r.subtitleKey).toBe('zz');
  });

  it('handles dotted base filenames (S01E01-style)', () => {
    const r = parseSubtitleFilename('Some Show.S01E01.Episode Name.en.srt', langMap);
    expect(r.langCode).toBe('en');
    expect(r.subtitleKey).toBe('English');
  });

  it('returns null when filename is not a subtitle', () => {
    expect(parseSubtitleFilename('movie.mp4', langMap)).toBeNull();
    expect(parseSubtitleFilename('srt', langMap)).toBeNull();
  });

  it('works without a langMap', () => {
    const r = parseSubtitleFilename('Movie.fr.auto.srt');
    expect(r.langCode).toBe('fr');
    expect(r.langName).toBe('fr');
    expect(r.subtitleKey).toBe('fr - Auto Generated');
    expect(r.isAutoGenerated).toBe(true);
  });
});
